# Generated by Django 4.0.5 on 2022-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='extra',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birthday',
            field=models.DateField(),
        ),
    ]
