# Generated by Django 4.0.5 on 2022-07-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_extra_alter_athlete_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('кроль', 'Freestyle'), ('дельфин', 'Butterfly'), ('на спине', 'Backstroke'), ('брасс', 'Breaststroke'), ('комплекс', 'Medley')], default='кроль', max_length=16)),
                ('time', models.DurationField()),
                ('distance', models.PositiveIntegerField()),
            ],
        ),
    ]
